# services:
#   db:
#     image: mariadb:10.6
#     restart: always
#     environment:
#       MYSQL_DATABASE: test_migrations
#       MYSQL_ROOT_PASSWORD: kali
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

#   redis:
#     image: redis:alpine
#     ports:
#       - "6378:6379"

#   migrate:
#     build: ./backend
#     env_file:
#       - ./backend/.env
#     depends_on:
#       - db
#     command: >
#       sh -c "
#       while ! nc -z db 3306; do sleep 2; done;
#       alembic upgrade head
#       "

#   api:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     env_file:
#       - ./backend/.env
#     depends_on:
#       - db
#       - redis
#       - migrate

#   celery:
#     build: ./backend
#     command: celery -A celery_app worker --beat --loglevel=info
#     env_file:
#       - ./backend/.env
#     depends_on:
#       - db
#       - redis
#       - api

#   task-dispatch-pro:
#     build: ./task-dispatch-pro
#     ports:
#       - "6057:6057"
#     depends_on:
#       - api

#   worker-insight-hub:
#     build: ./worker-insight-hub
#     ports:
#       - "5679:5679"
#     depends_on:
#       - api

# volumes:
#   mysql_data:



services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: test_migrations
      MYSQL_ROOT_PASSWORD: kali
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3387:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6398:6379"

  migrate:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: >
      sh -c "
      while ! nc -z db 3306; do sleep 2; done;
      alembic upgrade head
      "

  api:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
      - migrate

  seed-admin:
    build: ./backend
    command: >
      sh -c "
      while ! nc -z db 3306; do sleep 2; done;
      python3 seed_admin.py
      "
    env_file:
      - ./backend/.env
    depends_on:
      - api
      - db
  # celery:
  #   build: ./backend
  #   command: celery -A celery_app worker --beat --loglevel=info
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - db
  #     - redis
  #     - api
  celery:
    build: ./backend
    command: celery -A celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
      - api

  celery-beat:
    build: ./backend
    command: celery -A celery_app beat --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
      - api

  task-dispatch-pro:
    build: ./task-dispatch-pro
    ports:
      - "6057:6057"
    depends_on:
      - api

  worker-insight-hub:
    build: ./worker-insight-hub
    ports:
      - "5679:5679"
    depends_on:
      - api

volumes:
  mysql_data: